version: '3.8'

services:
  postgres-product:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"

  postgres-order:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-product

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres-order
      - product-service